config/routes.rb
Rails.application.routes.draw do
  resources :categories, path: "", only: [] do
    resources :events, path: "", only: :index
  end

  root to: 'events#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :events

  scope :ordered, -> { order :name }

  validates :name, uniqueness: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.navigable(number)
    navigable_ids = joins(:events).group(:id)
                                  .order('count_all desc')
                                  .count
                                  .take(number)
                                  .map &:first
    find navigable_ids
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :category

  scope :ordered, -> { order tweet_id: :desc }

  validates :tweet_id, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

module Authentication
  extend ActiveSupport::Concern

  included do
    http_basic_authenticate_with auth_options if auth_enabled?
  end

  class_methods do
    def auth_enabled?
      ENV['AUTH_NAME'] && ENV['AUTH_PASSWORD']
    end

    def auth_options
      {
        name: ENV['AUTH_NAME'],
        password: ENV['AUTH_PASSWORD']
      }
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  MAX_EVENTS = 60

  def index
    @events = find_events.ordered.limit MAX_EVENTS
  end

  private

  def find_category
    Category.friendly.find params[:category_id] if params[:category_id]
  end

  def find_events
    (category = find_category) ? category.events : Event.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  NAVIGABLE_NUMBER = 7

  def navigable_categories
    @navigable_categories ||= Category.navigable NAVIGABLE_NUMBER
  end
end

app/views/application/_footer.html.erb
<footer>
  <p>
    Contacto: <%= mail_to "infoartebarato@gmail.com" %>
  </p>
</footer>

app/views/application/_nav.html.erb
<nav>
  <%= link_to root_url, class: "brand" do %>
    <span>Arte Barato</span>
  <% end %>

  <input id="bmenub" type="checkbox" class="show">
  <label for="bmenub" class="burger pseudo button">&#9776;</label>

  <div class="menu">
    <% navigable_categories.each do |category| %>
      <%= link_to category.name, category_events_url(category), class: "button pseudo" %>
    <% end %>
  </div>
</nav>

app/views/events/_event.html.erb
<div class="event">
  <article class="card">
    <p>
      <%= auto_link event.tweet_text %>
    </p>
  </article>
</div>

app/views/events/index.html.erb
<%= render @events %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arte Barato</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "nav" %>

    <main>
      <div class="flex one two-500 three-1000">
        <%= yield %>
      </div>
    </main>

    <%= render "footer" %>
  </body>
</html>